### PR TITLE
Utility to change annotation box background color

### PR DESCRIPTION
**Pull request by joshua-dean**
# Utility to change annotation box background color

## Description

Added a function (swap_anno_bg_color) that changes the color of the annotation box.
Some images need higher contrast backgrounds so they don't blend in to the default black.

## PR Checklist

- [X] Merged latest master
- [X] Version number in `package.json` has been bumped since last release
- [X] Version numbers match between package `package.json` and `src/version.js`
- [X] Ran `npm install` and `npm run build` AFTER bumping the version number
- [X] Updated documentation if necessary (currently just in `api_spec.md`)
- [X] Added changes to `changelog.md`

## Breaking API Changes

None.

### CODE REVIEW

**Comment by joshua-dean** [comment]
I was running on npm 6.x instead of 7, which have different formats for package-lock.json and was making a pretty large diff. Last 2 commits fixed this.

**Comment by joshua-dean** [comment]
I forgot to update the package-lock and rebuild correctly, everything should be fixed now so the total diff size for this PR is what it should be.

**Comment by neheller** [comment]
Looks good, I just made a couple of minor changes -- I'm told we should avoid `var` where possible. I also ran `npm update` because that's overdue.

About the changelog, the way I've been using it is keeping all new changes in [unreleased] until the new release is actually out and published on npm. After that's done, then I add a new heading.

**Review by neheller — APPROVED** [review]
See comment above.

**Pull request merged**
